# Base configs

baseurl: ""

# UI configs
title: "Nikhil Sarkhedi"
author: "Nikhil Sarkhed"
about: "programmer"
social_urls:
  facebook: "https://www.facebook.com/nikhil.sarkhedi"
  twitter: "#"
  instagram: "https://www.instagram.com/nik_sarkhedi/"

  
  
