# Base configs
baseurl:"niksarkhedi"

# UI configs
title: "Nikhil Sarkhedi"
author: "Nikhil Sarkhedi"
about: "A Pythonista"
social_urls:
    Gmail:"niksarkhedi@gmail.com"
    facebook:"https://www.facebook.com/nikhil.sarkhedi"
    instagram:"https://www.instagram.com/nik_sarkhedi/"
    Github:"niksarkhedi"

  
  
